# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

 source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'Token' do
    pod 'Alamofire', '~> 4.7'
 pod 'SwiftyJSON', '~> 4.0'
pod 'Toast-Swift', '~> 3.0.1'

end